### ISSUE TITLE
Questions on the implementation of a linear variant and reference

### ISSUE THREAD

**Issue by scaomath** [lucidrains/linear-attention-transformer#8]
In the setup that is not Linformer:
https://github.com/lucidrains/linear-attention-transformer/blob/dd3f7b63fe2235cba97ab1a95840d0484c70c068/linear_attention_transformer/linear_attention_transformer.py#L337-L338

The `SelfAttention` function uses 
```python
def linear_attn(q, k, v, kv_mask = None):
    dim = q.shape[-1]

    if exists(kv_mask):
        mask_value = max_neg_value(q)
        mask = kv_mask[:, None, :, None]
        k = k.masked_fill_(~mask, mask_value)
        v = v.masked_fill_(~mask, 0.)
        del mask

    q = q.softmax(dim=-1)
    k = k.softmax(dim=-2)

    q = q * dim ** -0.5

    context = einsum('bhnd,bhne->bhde', k, v)
    attn = einsum('bhnd,bhde->bhne', q, context)
    return attn.reshape(*q.shape)
```
May I know which paper exactly is this linear attention implementing? @lucidrains 
Also I have a noob question: is `torch.einsum` more efficient than matmul, can't we just use `Softmax(Q)( Softmax(K^T) V)`?
Greatly appreciated.

-Shuhao

**Comment by charlesxu90** [comment]
Met with the same question. 

For others as a reference. The main figure comes from [Efficient Attention: Attention with Linear Complexities
](https://arxiv.org/abs/1812.01243) So this attention variant should be come from this paper.
